# curl --location 'http://127.0.0.1:8000/api/cart/initiate?XDEBUG_SESSION_START=PHPSTORM'
#--header 'Content-Type: application/json'
#--data '{
#    "customerId": customer id from db
#}'
# Initiate cart request
POST http://127.0.0.1:8000/api/cart/initiate
Content-Type: application/json

{
    "customerId": 20
}

###

# curl --location 'http://127.0.0.1:8000/api/cart/addToCart?XDEBUG_SESSION_START=PHPSTORM'
#--header 'Content-Type: application/json'
#--data '{
#    "cartId": "025cd9c4-53e8-4f45-94cc-8114c0eaf98c", # Cart ID from db
#    "sku": "7f939d0b-a0ea-4d9e-8c63-d3dfa5a660f4", # Product sku from db
#    "quantity": 3
#}'
POST http://127.0.0.1:8000/api/cart/addToCart
Content-Type: application/json

{
    "cartId": "025cd9c4-53e8-4f45-94cc-8114c0eaf98c",
    "sku": "7f939d0b-a0ea-4d9e-8c63-d3dfa5a660f4",
    "quantity": 3
}
